### ISSUE TITLE
Export anonymised data to WorldFish dataverse and/or GARDIAN

### ISSUE THREAD

**Issue by efcaguab** [WorldFishCenter/peskas.timor.data.pipeline#21]
As part of the funding requirements data needs to be available. Once data has been cleaned and curated, we need to anonymise it and export it to a public repository. 

Te priority and details about the implementation still need to be discussed.

**Comment by efcaguab** [comment]
Looks like Dataverse might be a good start. The WorldFish repository is here https://dataverse.harvard.edu/dataverse/worldfish and there should be a way to have an API connected there to upload and update datasets we can start exploring

**Comment by langbart** [comment]
Closed by #52
