### ISSUE TITLE
Improve validation of prices

### ISSUE THREAD

**Issue by efcaguab** [WorldFishCenter/peskas.timor.data.pipeline#63]
Currently the only validation of revenue (and prices) is removing large or small values. Once we have the catch data we can use that to estimate the price of a catch and identify those that might be too large or too small for the catch. 

This is important because there was some confusion with the data collection that caused some prices to be collected in different ways (total, per weight, per individual). Doing this smarter validation will allow us to filter inadequate cases with more ease.

**Comment by langbart** [comment]
Closed by #73
