### ISSUE TITLE
Main pipeline failing

### ISSUE THREAD

**Issue by efcaguab** [WorldFishCenter/peskas.timor.data.pipeline#65]
The main pipeline is failing because there seems to be a problem with the rfishbase and the data download. See for example: https://github.com/WorldFishCenter/peskas.timor.data.pipeline/actions/runs/1168646086 

@langbart, do you mind having a look at what might be causing this problem and solving it?

**Comment by langbart** [comment]
@efcaguab it seems that rfishbase was recently rewritten and updated based on a RESTful API. It works locally after updating the package but I'm having troubles loading the latest version from Dockerfile and run it into the pipeline. I had several attempts without success at the moment. Do you know how to load a specific pkg version in Dockerfile according to the current configuration?

**Comment by efcaguab** [comment]
Thanks for fining out what was the issue! There are a couple things I would try. 

If the updated package is on CRANOne would be to install the package after the others using a specific date for the RStudio Package Manager (https://packagemanager.rstudio.com/client/#/repos/2/overview). Another, probably better but more dangerous, option would be to update the R version, if I'm not mistaken the package versions are synched with the release date of the R version, but I'm not 100% sure. 

If the updated package is not on CRAN, then you can just install from GitHub if that's needed using the remotes package. Something like the line below should do the trick in the Dockerfile.

```
 RUN Rscript -e "remotes::install_github(...)"
```
